# Generated by Django 5.1.7 on 2025-03-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogCategory',
            new_name='BlogCategories',
        ),
    ]
