# Generated by Django 5.1.7 on 2025-03-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogcategories_options_blogpagecategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPageCategory',
            new_name='BlogPageCategories',
        ),
    ]
