# Generated by Django 5.1.7 on 2025-03-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_blogpagecategory_blogpagecategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcategories',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('grey', 'Grey')], default='gray', help_text='Background Color', max_length=6),
        ),
    ]
