# Generated by Django 5.1.7 on 2025-03-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='author_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_label',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_summary',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
