# Generated by Django 5.1.7 on 2025-03-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_author_image_homepage_hero_cta_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_label',
            field=models.TextField(blank=True),
        ),
    ]
