# Generated by Django 5.1.7 on 2025-03-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_hero_cta_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta_label',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_summary',
            field=models.TextField(max_length=500),
        ),
    ]
