# Generated by Django 5.1.7 on 2025-03-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_homepage_hero_cta_link_homepage_hero_cta_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_link',
            field=models.URLField(blank=True),
        ),
    ]
