# Generated by Django 5.1.7 on 2025-03-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_hero_cta_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='hero_cta_link',
            new_name='hero_cta_url',
        ),
    ]
