# Generated by Django 5.1.7 on 2025-03-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_hero_cta_label_homepage_cta_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='my_story_content',
            field=models.TextField(blank=True, max_length=800),
        ),
        migrations.AddField(
            model_name='homepage',
            name='my_story_heading',
            field=models.CharField(blank=True, default='My Story', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
